In [ ]:
with open('./drive/MyDrive/ReadMe.md','w') as f:
    data = f.write('* 반가워요 . ')
    print('저장되었습니다')
! pwd

저장되었습니다
/content


# 넘파이(numpy)

- ndim :축의 개수
- shape :배열의 차원정보
- size:배열 안에 있는 원소의 총개수
- dtype :배열 원소의 자료형

## 1차원과 속성들

In [ ]:
#pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim) # ndim:축의 개수
print(narry.shape) #shape:배열의 차원정보 (5,)
print(narry.size)  #size:배열 안에 있는 원소의 총 개수
print(narry.dtype) #dtype :배열 원소의 자료형
print(narry[3])
print(narry[2:4]) # <=X<

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [ ]:
narr1 = np.array([1,2,3,4]) #int64
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,3,4],dtype ='str') #배열 원소의 자료형 교환 int->str
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)


[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [ ]:
narr4 = np.zeros(10,dtype='int64') #초기화
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3) #세팅
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False,dtype='int64')
narr10 = np.arange(0,100,25)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))


[0 0 0 0 0 0 0 0 0 0] 1 int64 (10,) 10 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 25 50 75] 1 int64 (4,) 4 <class 'numpy.ndarray'>


## 2차원 배열

In [ ]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.array([[0,0,],[0,0]])
print(arr1,arr1.ndim , arr1.dtype,arr1.shape,arr1.size,type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [ ]:
arr2 =np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)

print(arr2,'차원:',arr2.ndim ,'/ 데이터타입:', arr2.dtype,'/형태:',arr2.shape,'/크기:',arr2.size,type(arr2))
print(arr3,'차원:',arr3.ndim ,'/ 데이터타입:', arr3.dtype,'/형태:',arr3.shape,'/크기:',arr3.size,type(arr3))
print(arr4,'차원:',arr4.ndim ,'/ 데이터타입:', arr4.dtype,'/형태:',arr4.shape,'/크기:',arr4.size,type(arr4))
print(arr5,'차원:',arr5.ndim ,'/ 데이터타입:', arr5.dtype,'/형태:',arr5.shape,'/크기:',arr5.size,type(arr5))
print(arr6,'차원:',arr6.ndim , '/ 데이터타입:',arr6.dtype,'/형태:',arr6.shape,'/크기:',arr6.size,type(arr6))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 차원: 2 / 데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] 차원: 2 / 데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 차원: 2 / 데이터타입: int64 /형태: (2, 5) /크기: 10 <class 'numpy.ndarray'>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 차원: 2 / 데이터타입: int64 /형태: (5, 2) /크기: 10 <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 차원: 3 / 데이터타입: int64 /형태: (3, 3, 3) /크기: 27 <class 'numpy.ndarray'>


In [ ]:
t1 = np.arange(1,22).reshape(3,7)
arr2 = np.arange(1,8).reshape(7,1)
arr3 = np.arange(1,11).reshape(5,2)
arr4 = np.arange(1,22).reshape(3,7)
arr5 = np.arange(1,13).reshape(4,3,1)
print(t1)
print("="*15)
print(arr2)
print("="*15)
print(arr3)
print("="*15)
print(arr4)
print("="*15)
print(arr5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [ ]:
#test
print(t1[1][2:5])
print(arr4 [0][3:7])
print(arr4[1][3:7])
print(arr4[2][3:7])
print([arr4>12])
#true or false 뱉어내는 기능
print(arr4 % 2 ==0 )

[10 11 12]
[4 5 6 7]
[11 12 13 14]
[18 19 20 21]
[array([[False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [ ]:
# np 배열 연산 //shape(배열차원)이 같은 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈:",np1+np2)
print("뺄셈:",np1-np2)
print("곱셈:",np1*np2)
print("나눗셈:",np1/np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
#브로드캐스팅
np3 = np1 +10
print(np3)

[16 17 18 19 20]


In [ ]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
#스칼라와 연산
print("=======스칼라와 연산=======")
print(br1)
print(br1*3)
print(br1*2)
#2D 와 1D의 연산
print("=======2D와 1D의 연산=======")
print(br1+br2)
print(br1*br2)

=======스칼라와 연산=======
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=======2D와 1D의 연산=======
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [ ]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(1,9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#구글 제미나의 AI
from google import genai

client = genai.Client(api_key="YOUR_API_KEY")

response = client.models.generate_content(
    model="gemini-2.0-flash",
    contents="Explain how AI works",
)

print(response.text)