In [ ]:
with open('./drive/MyDrive/ReadMe.md','w') as f:
    data = f.write('* 반가워요 . ')
    print('저장되었습니다')
! pwd

저장되었습니다
/content


# 넘파이(numpy)

- ndim :축의 개수
- shape :배열의 차원정보
- size:배열 안에 있는 원소의 총개수
- dtype :배열 원소의 자료형

## 1차원과 속성들

In [ ]:
#pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim) # ndim:축의 개수
print(narry.shape) #shape:배열의 차원정보 (5,)
print(narry.size)  #size:배열 안에 있는 원소의 총 개수
print(narry.dtype) #dtype :배열 원소의 자료형
print(narry[3])
print(narry[2:4]) # <=X<

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [ ]:
narr1 = np.array([1,2,3,4]) #int64
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,3,4],dtype ='str') #배열 원소의 자료형 교환 int->str
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)


[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [ ]:
narr4 = np.zeros(10,dtype='int64') #초기화
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3) #세팅
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False,dtype='int64')
narr10 = np.arange(0,100,25)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))


[0 0 0 0 0 0 0 0 0 0] 1 int64 (10,) 10 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 25 50 75] 1 int64 (4,) 4 <class 'numpy.ndarray'>


## 2차원 배열

In [ ]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.array([[0,0,],[0,0]])
print(arr1,arr1.ndim , arr1.dtype,arr1.shape,arr1.size,type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [ ]:
arr2 =np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)

print(arr2,'차원:',arr2.ndim ,'/ 데이터타입:', arr2.dtype,'/형태:',arr2.shape,'/크기:',arr2.size,type(arr2))
print(arr3,'차원:',arr3.ndim ,'/ 데이터타입:', arr3.dtype,'/형태:',arr3.shape,'/크기:',arr3.size,type(arr3))
print(arr4,'차원:',arr4.ndim ,'/ 데이터타입:', arr4.dtype,'/형태:',arr4.shape,'/크기:',arr4.size,type(arr4))
print(arr5,'차원:',arr5.ndim ,'/ 데이터타입:', arr5.dtype,'/형태:',arr5.shape,'/크기:',arr5.size,type(arr5))
print(arr6,'차원:',arr6.ndim , '/ 데이터타입:',arr6.dtype,'/형태:',arr6.shape,'/크기:',arr6.size,type(arr6))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 차원: 2 / 데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] 차원: 2 / 데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 차원: 2 / 데이터타입: int64 /형태: (2, 5) /크기: 10 <class 'numpy.ndarray'>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 차원: 2 / 데이터타입: int64 /형태: (5, 2) /크기: 10 <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 차원: 3 / 데이터타입: int64 /형태: (3, 3, 3) /크기: 27 <class 'numpy.ndarray'>


In [ ]:
t1 = np.arange(1,22).reshape(3,7)
arr2 = np.arange(1,8).reshape(7,1)
arr3 = np.arange(1,11).reshape(5,2)
arr4 = np.arange(1,22).reshape(3,7)
arr5 = np.arange(1,13).reshape(4,3,1)
print(t1)
print("="*15)
print(arr2)
print("="*15)
print(arr3)
print("="*15)
print(arr4)
print("="*15)
print(arr5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [ ]:
#test
print(t1[1][2:5])
print(arr4 [0][3:7])
print(arr4[1][3:7])
print(arr4[2][3:7])
print([arr4>12])
#true or false 뱉어내는 기능
print(arr4 % 2 ==0 )

[10 11 12]
[4 5 6 7]
[11 12 13 14]
[18 19 20 21]
[array([[False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [ ]:
# np 배열 연산 //shape(배열차원)이 같은 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈:",np1+np2)
print("뺄셈:",np1-np2)
print("곱셈:",np1*np2)
print("나눗셈:",np1/np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
#브로드캐스팅
np3 = np1 +10
print(np3)

[16 17 18 19 20]


In [ ]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
#스칼라와 연산
print("=======스칼라와 연산=======")
print(br1)
print(br1*3)
print(br1*2)
#2D 와 1D의 연산
print("=======2D와 1D의 연산=======")
print(br1+br2)
print(br1*br2)

=======스칼라와 연산=======
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=======2D와 1D의 연산=======
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [ ]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(1,9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#구글 제미나의 AI
from google import genai

client = genai.Client(api_key="YOUR_API_KEY")

response = client.models.generate_content(
    model="gemini-2.0-flash",
    contents="Explain how AI works",
)

print(response.text)

# 판다스(pandas)

- 시리즈(series) #한개 있으면 시리즈
- 데이터프레임(dataframe) #여러개있으면 데이터프레임

In [ ]:
#!pip install pandas 

In [2]:
import numpy as np 
import pandas as pd 

In [17]:
#판다스 기초,
data1 = np.arange(1,6)
print(data1)
data2 = pd.Series(data1)
print(data2,type(data2),data2.index,data2.values,data2.dtype)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=5, step=1) [1 2 3 4 5] int64


In [14]:
# 판다스 시리즈의 데이터타입 
data3 = pd.Series([1,2,3.14,4,5,6,7])#,dtype="float")
#하나의 데이터 값을 기준으로 모두의 자료형이 변환됨 3.14 때문에 int가 float이 됨 
print(data3)

0    1.00
1    2.00
2    3.14
3    4.00
4    5.00
5    6.00
6    7.00
dtype: float64


In [16]:
# 판다스 시리즈의 인덱스설정
data3 = pd.Series([1,2,3,4],index=['a','b','c','d'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [30]:
# 판다스 시리즈 딕셔너리데이터 
population_dict = {
    'korea' :5182,
    'japan' :12622,
    'china' :141178,
    'usa' :32976
}
# population_dict.keys() #. keys()함수 -기능을 담고 있으므로 수행 
# population_dict.values()
# population_dict.items()
country = pd.Series(population_dict)
print(country,country.index,country.values) #. index 속성 - 특징들을 말함 
print(country.ndim, country.shape,country.size)
# 시리즈 원소에 접근 방법 
print(country.loc['usa'])
print(country.iloc[3])

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
32976
32976


In [32]:
# 판다스 데이터프레임 
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['A','B','C']) #가로 :칼럼 #세로 :행:인덱스 라 하심 
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [49]:
# 테스트 
import numpy as np 
import pandas as pd

# 두 개의 시리즈 데이터 
print("인구수 시리즈 데이터:")
population_dict = {
    'korea' :5182,
    'japan' :12622,
    'china' :141178,
    'usa' :32976
}
population = pd.Series(population_dict)
print(population)

print("GDP 시리즈 데이터:")
GDP_dict = {
    'korea' :169320000,
    'japan' :516700000,
    'china' :140925000,
    'usa' :2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print("="*25)
print("데이터 프레임 생성:")
country = pd.DataFrame({'population':population,'gdp':GDP})
country.index.name ="Country" #인덱스 이름 지정 
country.columns.name = "Info" #컬럼 이름 지정
print(country.index,country.columns)
print(country.values,country.shape,country.size,country.ndim) #(4,2) #4층 2칸 셰입 #축개수 ndim 2개   

인구수 시리즈 데이터:
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터:
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성:
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='Info')
[[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]] (4, 2) 8 2


In [56]:
#데이터 프레임의 요소 접근 방법,loc, iloc 
country.loc['korea'],country.loc['usa'] #loc는 키값 기반 
country.iloc[2],country.iloc[1] #iloc는  인덱스 기반 

(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 gdp           516700000
 Name: japan, dtype: int64)

In [62]:
country.loc['korea':'japan',:'population'] # <=x <= 

Info     population
Country            
korea          5182
japan         12622

In [66]:
country.iloc[0:2,:1] #<=x<

Info     population
Country            
korea          5182
japan         12622

In [64]:
country

Info     population         gdp
Country                        
korea          5182   169320000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000

In [71]:
# 컬럼 추가 
# country['test'] = [11,22,33,44]
# country = country.drop('test',axis=1) #1은 세워진 세로 , 칼럼 
gdpper = country['gdp'] /country['population']
country['gdp_per'] = gdpper
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326

In [87]:
# 행추가 1
country.loc['india'] = [142222,150505000,121121]
country.loc['india','gdp_per'] = country.loc['india','gdp']/country.loc['india','population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935

In [88]:
# 행추가 방법2 
africa = pd.Series(data =[123456,7777777],index=['population','gdp'])
country.loc['africa'] = africa
country.loc['africa','gdp_per'] = country.loc['africa','gdp']/country.loc['africa','population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935
africa     123456.0  7.777777e+06     63.000397

In [89]:
#결측값(Nan) 확인 
country.isnull() #.sum()

Info     population    gdp  gdp_per
Country                            
korea         False  False    False
japan         False  False    False
china         False  False    False
usa           False  False    False
india         False  False    False
africa        False  False    False

In [90]:
# 열제거 drop('이름', axis = 0) 
country = country.drop('africa',axis=0) #inplace =True # 원본을 바꿈 
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935

In [91]:
#테스트 1 조건 
country[country['population'] >140000]

Info     population          gdp      gdp_per
Country                                      
china      141178.0  140925000.0   998.207936
india      142222.0  150505000.0  1058.239935

In [99]:
#테스트 2 조건 , 슬라이싱 (loc,iloc 필수 )
country[(country['population']>10000 )& (country['population'] < 100000)].loc[:,:'population']

Info     population
Country            
japan       12622.0
usa         32976.0

### 문제 1 
- 다음 데이터가 담긴 데이터 프레임을 만들어라 
### 문제 2
- 박철수만 출력하라
### 문제 3 
- 수학이 70점 이상인 사람 모든 행을 출력하라
### 문제 4 
- 모든 과목의 평균 점수를 마지막 컬럼에 넣고 "평균" 이라는 이름으로 만들어 넣어라
### 문제 5 
- 전학 온 학생을 추가하라 (최자바 55 95 70) 

In [128]:
# 기본적인 방법 
data = {
    '이름' : ['홍길동','박철수','김영희'],
    '국어' : [80,60,70],
    '수학' : [70,70,90],
    '영어' : [80,80,80]
}
df = pd.DataFrame(data)
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [144]:
# 키값쌍으로 리스트에 저장하는 방법 
data = [
    {'이름' : '홍길동','국어':80,'수학':70,'영어':80},
    {'이름' : '박철수','국어':60,'수학':70,'영어':80},
    {'이름' : '김영희','국어':70,'수학':90,'영어':80},
]
df = pd.DataFrame(data)
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [146]:
# 리스트에 튜플로 저장하는 방법 
data = [
    ('홍길동',80,70,80),
    ('박철수',60,70,80),
    ('김영희',70,90,80)
]
df = pd.DataFrame(data,columns=['이름','국어','수학','영어'])
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [158]:
# import numpy as np 
# data0 = [
#     ('홍길동',80,70,80),
#     ('박철수',60,70,80),
#     ('김영희',70,90,80)
# ]
# data = np.array(data0)
data = np.array([['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80]])
df = pd.DataFrame(data,columns=['이름','국어','수학','영어'])

In [157]:
#문제 1번 
df

0   1   2   3
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [138]:
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [159]:
#문제 2번 
df.iloc[1:2]
df.loc[1:2]

이름  국어  수학  영어
1  박철수  60  70  80
2  김영희  70  90  80

In [163]:
#문제 3번 
#넘파이는 하나의 요소가 문자이면 나머지 요소들의 자료형도 모두 문자로 바꿔버리므로 
#후에 요소 값 구분 어려움 ? 
print(df[df['국어'].astype(int)>=70])
# df[df['국어'] >=70]

    이름  국어  수학  영어
0  홍길동  80  70  80
2  김영희  70  90  80


In [151]:
#문제 4번 
df['평균'] = (df['국어']+df['수학']+df['영어'])/3
print('평균',df['평균'].dtype)
df.round()

평균 float64


이름  국어  수학  영어    평균
0  홍길동  80  70  80  77.0
1  박철수  60  70  80  70.0
2  김영희  70  90  80  80.0

In [155]:
#문제 5번 
df.loc[3] = ('최자바',55,95,70,77) 
df

이름  국어  수학  영어         평균
0  홍길동  80  70  80  76.666667
1  박철수  60  70  80  70.000000
2  김영희  70  90  80  80.000000
3  최자바  55  95  70  77.000000